name: Docker CI Pipeline

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_REPO }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release tag
        id: get_release
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Build the docker image
        run: docker build . --file Dockerfile --tag $DOCKER_HUB_REPO/canipay-be:latest

      - name: Login docker hub
        run: echo "$DOCKER_HUB_TOKEN" | docker login --username $DOCKER_HUB_REPO --password-stdin

      - name: Push to docker hub repository
        run: |
          docker push $DOCKER_HUB_REPO/canipay-be:latest
          docker tag $DOCKER_HUB_REPO/canipay-be:latest $DOCKER_HUB_REPO/canipay-be:${{ env.TAG }}
          docker push $DOCKER_HUB_REPO/canipay-be:${{ env.TAG }}
